# Generated by Django 6.0 on 2026-01-14 06:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='recipe',
            name='name',
            field=models.CharField(max_length=300),
        ),
        migrations.AlterField(
            model_name='recipeingredient',
            name='measure',
            field=models.CharField(max_length=300),
        ),
    ]
