# Generated by Django 6.0 on 2026-01-14 10:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0003_alter_ingredient_ingredient_type_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='recipe',
            name='area',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='recipe',
            name='thumbnail',
            field=models.URLField(blank=True, max_length=500),
        ),
        migrations.AlterField(
            model_name='recipe',
            name='youtube_link',
            field=models.URLField(blank=True, max_length=500, null=True),
        ),
    ]
