# Generated by Django 6.0 on 2026-01-14 10:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0004_alter_recipe_area_alter_recipe_thumbnail_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='thumbnail',
            field=models.URLField(blank=True, max_length=500),
        ),
    ]
